ALTER TABLE "WorkoutPlanDay"
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "AgentActionProposal"
ADD COLUMN "executedAt" TIMESTAMP(3),
ADD COLUMN "basePlanId" TEXT,
ADD COLUMN "basePlanVersion" INTEGER,
ADD COLUMN "basePlanUpdatedAt" TIMESTAMP(3),
ADD COLUMN "expectedDayId" TEXT,
ADD COLUMN "expectedDayUpdatedAt" TIMESTAMP(3);
